"""
Typing definitions for the Milter module
"""

import typing

def uniqueID() -> int: ...

CONTINUE: int
REJECT: int

class Base:
    def envfrom(self, f: str, *s: str) -> int: ...
    def envrcpt(self, to: str, *s: str) -> int: ...
    def header(self, field: str, value: str) -> int: ...
    def eoh(self) -> int: ...
    def eom(self) -> int: ...
    def setreply(self, rcode: str, xcode: str | None = None, msg: str | None = None, *ml: str) -> None: ...

factory: typing.Callable[[], Base]

def set_flags(flags: int) -> None: ...

def runmilter(name: str, socketname: str, timeout: int = 0, rmsock: bool = True) -> typing.Never: ...

